aws_region           = "us-east-1"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.0.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.1.0/24", "10.0.3.0/24"]
azs                  = ["us-east-1a", "us-east-1b"]
project_name         = "secure-app"
ssh_key_name         = "lab"
public_alb_name  = "public-alb"
internal_alb_name = "private-alb"  
ssh_private_key_path = "C:/Users/Moaaz/.ssh/lab.pem"
